#!/usr/bin/env perl

use Git;

print %ENV; # Print them anyway for debug
if ( $ENV{'PUSH'} ne 'true' ) {
  my $repo = Git->repository (Directory => '.');
  my @modified_files = $repo->command('diff', "--name-only", "HEAD", "HEAD^");
  die("No Dockerfile modified in the last commit\n")  unless grep( /Dockerfile/, @modified_files);
}
